name: Proxy Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions: write-all
    name: Build and upload
    runs-on: ubuntu-latest
    container:
      image: messense/rust-musl-cross:x86_64-musl
    steps:
      - name: Check for dockerenv file
        run: |
          pwd
          cargo -V
          uname
          whoami